spring:
  profiles:
    active: local
---
server:
  port: 8009

spring:
  config:
    activate:
      on-profile: local

  datasource:
    initialization-mode: always # always 초기화 이후 never 로 변경
    schema: classpath:db/schema.sql
    url: jdbc:h2:tcp://localhost/~/core
    username: sa
    password:
    driver-class-name: org.h2.Driver

  quartz:
    overwrite-existing-jobs: true
    scheduler-name: external-scheduler
    jdbc:
      initialize-schema: always # always 초기화 이후 never 로 변경
      schema: classpath:db/schema.sql