spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    internal:
      hikari:
        jdbc-url: jdbc:h2:tcp://localhost/~/internal
        username: sa
        password: #local - password
        minimum-idle: 10
        maximum-pool-size: 10
        driver-class-name: org.h2.Driver
      jpa:
        persistence-unit-name: internal
        entity-path: com.internal.entity
        database-platform: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
        format-sql: true # 쿼리 형태를 보정
        show-sql: false # true 로 설정시 System.out 로 출력되기에 좋지 않다.

    external:
      hikari:
        jdbc-url: jdbc:h2:tcp://localhost/~/external
        username: sa
        password: #local - password
        minimum-idle: 10
        maximum-pool-size: 10
        driver-class-name: org.h2.Driver
      jpa:
        persistence-unit-name: external
        entity-path: com.external.entity
        database-platform: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
        format-sql: true # 쿼리 형태를 보정
        show-sql: false # true 로 설정시 System.out 로 출력되기에 좋지 않다.

    scheduler:
      hikari:
        jdbc-url: jdbc:h2:tcp://localhost/~/scheduler
        username: sa
        password: #local - password
        minimum-idle: 10
        maximum-pool-size: 10
        driver-class-name: org.h2.Driver
    quartz:
      overwrite-existing-jobs: true
      scheduler-name: scheduler
      jdbc:
        initialize-schema: always # always 초기화 이후 never 로 변경
        schema: classpath:db/schema.sql

logging.level:
  org.hibernate.SQL: debug