spring:
  profiles:
    active: local

---
## docker install
# docker pull postgres
# docker run --name internal -d -p 5432:5432 -e POSTGRES_PASSWORD="1234" postgres
# docker run --name external -d -p 5433:5432 -e POSTGRES_PASSWORD="1234" postgres

spring:
  config:
    activate:
      on-profile: local

  quartz:
    overwrite-existing-jobs: true
    scheduler-name: scheduler
    job-store-type: jdbc
    jdbc:
      initialize-schema: always # always 초기화 이후 never 로 변경
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

  batch:
    initialize-schema: always
    job:
      enabled: false

  internal:
    datasource:
      hikari:
        jdbc-url: jdbc:postgresql://localhost:5432/internal?reWriteBatchedInserts=true
        username: postgres
        password: 1234
        minimum-idle: 10
        maximum-pool-size: 50
        driver-class-name: org.postgresql.Driver
        data-source-properties:
          rewriteBatchedStatements: true
      jpa:
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
          hibernate:
            format_sql: true
            jdbc:
              batch_size: 1000
            order_inserts: true
            order_updates: true

  external:
    datasource:
      hikari:
        jdbc-url: jdbc:postgresql://localhost:5433/external
        username: postgres
        password: 1234
        minimum-idle: 10
        maximum-pool-size: 50
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        properties:
          hibernate:
            format_sql: true

    ## internal 설정을 의존성을 가지도록 설정
    ## 다른 디비에 의존해야 한다면 데이터소스 생성하여 주입하여야함.
    scheduler:
      hikari:
        jdbc-url: jdbc:h2:tcp://localhost/~/scheduler
        username: sa
        password: #local - password
        minimum-idle: 10
        maximum-pool-size: 10
        driver-class-name: org.h2.Driver

logging.level:
  org.hibernate.SQL: debug