spring:
  profiles:
    active: local

server:
  port: 8001

---
## quartz
spring:
  profile: core

  datasource:
    initialization-mode: never # always 초기화 이후 never 로 변경
    schema: classpath:db/schema.sql
    core:
      jdbc-url: jdbc:h2:tcp://localhost/~/core
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
